inherit_gem:
  rubocop-govuk:
    - config/default.yml

require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6

RSpec/ImplicitSubject:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 6
